sudo: required
language: bash
services:
  - docker
install: true

before_install:
  - openssl aes-256-cbc -K $encrypted_d91c90adac2d_key -iv $encrypted_d91c90adac2d_iv -in .stuff.tar.gz.enc -out stuff.tar.gz -d
  - file stuff.tar.gz
  - tar xzvf stuff.tar.gz -C /tmp/
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/stuff/.deploy
  - ssh-add /tmp/stuff/.deploy
  - mv /tmp/stuff/.host ~/.ssh/config
  - sudo apt-get install qemu-utils kpartx util-linux

script:
  - docker build -t cloud .
  - docker create --name=cloud cloud
  - dd if=/dev/zero of=unity-cloud_raw.img bs=1 count=0 seek=3G
  - printf 'o\nn\np\n1\n\n\nw\n' | fdisk unity-cloud_raw.img
  - sudo kpartx -av unity-cloud_raw.img
  - mke2fs -t ext4 /dev/mapper/loop0p1
  - mkdir ./mnt
  - sudo mount -o loop /dev/mapper/loop0p1 ./mnt
  - docker export cloud | sudo tar x -C ./mnt
  - sudo mount ./mnt
  - sudo kpartx -dv unity-cloud_raw.img
  - IMG=$(find ~/ -name *.img)
  - qemu-img convert -c -f raw -O qcow2 $IMG ./unity-cloud_qcow2.qcow2
  - xz -9 $IMG
  - IMGXZ=$(find ~/ -name *.img.xz)
  - IMGQCOW=$(find ~/ -name *.qcow2)
  - mkdir ./build_cloud
  - mv $IMGXZ ./build_cloud/
  - mv $IMGQCOW ./build_cloud/

after_success:
  - rsync -arz --progress --delete --rsh=ssh -e "ssh -o StrictHostKeyChecking=no" ./build_cloud foobar2:public_html/pub/isos/ &
  - rsync -arz --progress --delete --rsh=ssh -e "ssh -o StrictHostKeyChecking=no" ./build_cloud foobar:/var/www/html/isos/
